al:
  sign:
    url: https://member.aliyundrive.com/v1/activity/sign_in_list?_rx-s=mobile
  update:
    url: https://auth.aliyundrive.com/v2/account/token
  refresh:
    token: 自己的refresh_token
server:
  port: 9099
spring:
  application:
    name: fcsummer-cloud-check
